In [1]:
%pip install pandas numpy loguru xlsxwriter
%pip install -e ../../PDFDataExtractor-lib

Requirement already satisfied: pandas in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (2.4.4)
Requirement already satisfied: loguru in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (0.7.3)
Requirement already satisfied: xlsxwriter in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (3.2.9)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: colorama>=0.3.4 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from loguru) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from loguru) (1.2.0)
Requirement already satisfied: six>=1.5 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Obtaining file:///C:/work/MEN_Marketing/04_PRG_20251111___OCR_Sys_perlettura_PDF/PDFDataExtractor-lib
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pdfplumber<0.12,>=0.11 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfdataextractor==0.2.2) (0.11.9)
Requirement already satisfied: pandas<3,>=2.2 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfdataextractor==0.2.2) (2.3.3)
Requirement already satisfied: numpy<3,>=2.1 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfdataextractor==0.2.2) (2.4.4)
Requirement already satisfied: scikit-learn<2,>=1.6 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfdataextractor==0.2.2) (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas<3,>=2.2->pdfdataextractor==0.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas<3,>=2.2->pdfdataextractor==0.2.2) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pandas<3,>=2.2->pdfdataextractor==0.2.2) (2025.3)
Requirement already satisfied: pdfminer.six==20251230 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (20251230)
Requirement already satisfied: Pillow>=9.1 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (12.1.1)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (5.6.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfminer.six==20251230->pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from pdfminer.six==20251230->pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (46.0.6)
Requirement already satisfied: scipy>=1.10.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from scikit-learn<2,>=1.6->pdfdataextractor==0.2.2) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from scikit-learn<2,>=1.6->pdfdataextractor==0.2.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from scikit-learn<2,>=1.6->pdfdataextractor==0.2.2) (3.6.0)
Requirement already satisfied: cffi>=2.0.0 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (2.0.0)
Requirement already satisfied: pycparser in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber<0.12,>=0.11->pdfdataextractor==0.2.2) (3.0)
Requirement already satisfied: six>=1.5 in c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=2.2->pdfdataextractor==0.2.2) (1.17.0)
Building wheels for collected packages: pdfdataextractor
  Building editable for pdfdataextractor (pyproject.toml): started
  Building editable for pdfdataextractor (pyproject.toml): finished with status 'done'
  Created wheel for pdfdataextractor: filename=pdfdataextractor-0.2.2-0.editable-py3-none-any.whl size=4954 sha256=5fd6f608fed9c036fc46211fb239a7a7be88c014f8a65c7fc50b814b8df7a681
  Stored in directory: C:\Users\ukg15381\AppData\Local\Temp\pip-ephem-wheel-cache-6n67onxl\wheels\9e\d8\c6\d358e10a1290b7caebdaa86e2d528e9ec86d95bf3be8a3d6a5
Successfully built pdfdataextractor
Installing collected packages: pdfdataextractor
  Attempting uninstall: pdfdataextractor
    Found existing installation: pdfdataextractor 0.2.2
    Uninstalling pdfdataextractor-0.2.2:
      Successfully uninstalled pdfdataextractor-0.2.2
Successfully installed pdfdataextractor-0.2.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sys
print(sys.executable)

c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\.venv\Scripts\python.exe

In [3]:
import json
from pathlib import Path
import sys
from loguru import logger

project_root = Path.cwd().parent  # notebook eseguito da /notebooks
sys.path.insert(0, str(project_root / "src"))
from pipeline.orchestrator import run_pipeline

logger.remove()
logger.add(sys.stderr, level="ERROR")

print(project_root)
config_path = project_root / "configs" / "pipeline" / "pipeline_config_DEC.local.sample.json"
print(config_path)

with open(config_path, encoding="utf-8") as f:
    config = json.load(f)

result = run_pipeline(config, project_root=project_root, publish=False)
print(result["df_final"].shape)
result["df_final"].head()

c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline
c:\work\MEN_Marketing\04_PRG_20251111___OCR_Sys_perlettura_PDF\PDFDataExtractor-pipeline\configs\pipeline\pipeline_config_DEC.local.sample.json

2026-04-01 13:10:52.550 | ERROR    | pipeline.domains.reconstruction.HeaderProcessor:estrai_nomi_colonne:416 - [ERRORE] Le righe non possono essere convertite in Header
2026-04-01 13:10:52.550 | ERROR    | pipeline.domains.reconstruction.HeaderProcessor:rinomina_colonne:370 - Il Fallback e il Vecchio Header non hanno la stessa lunghezza: OldHeader Length=[16] | Fallback Length=[8]
2026-04-01 13:10:52.550 | ERROR    | pipeline.stages.reconstruction:reconstruct_tables:137 - Errore:  Pagina N: [45] Colonne N: [16]Lunghezze non compatibili per rinomina colonne
2026-04-01 13:10:53.156 | ERROR    | pipeline.domains.reconstruction.HeaderProcessor:estrai_nomi_colonne:416 - [ERRORE] Le righe non possono essere convertite in Header

(1919, 23)

colonna_ordinata_post,page_num,capitolo,sottocapitolo,page_title,page_subtitle,page_subtitle_1,table_id,period_desc,period_start,item_agg_2,...,2025_act,2025_bdg,eur_vs_act,pct_vs_act,eur_vs_bdg,pct_vs_bdg,eur_delta,pct_delta,run_id,timestamp_utc
0,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,54551.0,0.188,8606.0,0.026,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,25618.0,0.182,12796.0,0.083,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
2,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,13931.0,0.192,-5861.0,-0.064,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
3,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,5529.0,0.111,4447.0,0.087,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
4,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,4344.0,0.253,1689.0,0.085,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910

In [4]:
result["df_final"]

colonna_ordinata_post,page_num,capitolo,sottocapitolo,page_title,page_subtitle,page_subtitle_1,table_id,period_desc,period_start,item_agg_2,...,2025_act,2025_bdg,eur_vs_act,pct_vs_act,eur_vs_bdg,pct_vs_bdg,eur_delta,pct_delta,run_id,timestamp_utc
0,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,54551.0,0.188,8606.0,0.026,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,25618.0,0.182,12796.0,0.083,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
2,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,13931.0,0.192,-5861.0,-0.064,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
3,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,5529.0,0.111,4447.0,0.087,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
4,2,OVERVIEW,OVERVIEW,MENARINI GROUP PERFORMANCES OVERVIEW,NaN,NaN,0,MONTH,2025-12-01,NaN,...,NaN,NaN,4344.0,0.253,1689.0,0.085,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1914,76,CELL_BIOLOGY,OVERVIEW,OTHER BUSINESS,NaN,NaN,1,YTD,2025-12-01,NaN,...,11491.0,16534.0,-4764.0,-0.293,-5042.0,-0.305,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1915,76,CELL_BIOLOGY,OVERVIEW,OTHER BUSINESS,NaN,NaN,1,YTD,2025-12-01,NaN,...,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1916,76,CELL_BIOLOGY,OVERVIEW,OTHER BUSINESS,NaN,NaN,1,YTD,2025-12-01,NaN,...,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1917,76,CELL_BIOLOGY,OVERVIEW,OTHER BUSINESS,NaN,NaN,1,YTD,2025-12-01,NaN,...,1765.0,2987.0,305.0,0.209,-1222.0,-0.409,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910
1918,76,CELL_BIOLOGY,OVERVIEW,OTHER BUSINESS,NaN,NaN,1,YTD,2025-12-01,NaN,...,13256.0,19521.0,-4460.0,-0.252,-6265.0,-0.321,NaN,NaN,23934f00-590a-40fa-84f7-0ed9cdd56b35,2026-04-01 11:10:26.766910